#! /bin/ksh

set -e

mkdir -p $HOME/bin $HOME/texmf/tex/generic
ln -sf /nobackup/awhsu/ChezWEB/cheztangle $HOME/bin/cheztangle
ln -sf /nobackup/awhsu/ChezWEB/chezweave $HOME/bin/chezweave
ln -sf /nobackup/awhsu/ChezWEB/chezwebmac.tex $HOME/texmf/tex/generic/
texhash

echo "ChezWEB installed successfully!"
